package com.automated_testing.Phone;

public enum Token {
	GUANGDONG,SICHUAN,ANHUI,JIANGSU,ZHEJIANG,SHANDONG,HUNAN,WUHAN,SHANGHAI,FUJIAN,HENAN,LIAONING,BEIJING,BEICHENG,HEBEI,CHONGQING,HEILONGJIANG,SHANXI,LIANTONG,HAINAN,GUANGXI,SHANXIHOME,NINGXIA,NEIMENGGU,JILIN,GANSU,GUIZHOU,JIANGXI,QINGHAI,TIANJIN
}
